### ISSUE TITLE
trying to make it work

### ISSUE THREAD

**Issue by sibelius** [geek-fun/jest-search#1]
```jsx
jest-search checking platform uname: Darwin arm64 +0ms
jest-search checking if binary exists: /app/node_modules/.cache/jest-search/elasticsearch-8.8.2 +1ms
jest-search downloading binary, url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-darwin-arm64.tar.gz, path: /app/node_modules/.cache/jest-search/elasticsearch-8.8.2 +0ms
  jest-search Downloaded /app/node_modules/.cache/jest-search/elasticsearch-8.8.2 +336ms
jest-search Starting elasticsearch 8.8.2, /app/node_modules/.cache/jest-search/elasticsearch-8.8.2 +1ms
jest-search checking the local elasticsearch:9600 startup: 30 +13ms
jest-search failed to start engine emit error: {"errno":-2,"code":"ENOENT","syscall":"spawn /app/node_modules/.cache/jest-search/elasticsearch-8.8.2/bin/elasticsearch","path":"/app/node_modules/.cache/jest-search/elasticsearch-8.8.2/bin/elasticsearch","spawnargs":["-p","/app/node_modules/.cache/jest-search/elasticsearch-8.8.2/server-pid","-Ecluster.name=jest-search-local","-Enode.name=jest-search-local","-Ehttp.port=9600","-Expack.security.enabled=false"]} +0ms
/app/node_modules/@geek-fun/jest-search/dist/src/engine.js:61
throw new Error('failed to start engine emit error');
```

const { startEngine, stopEngine } = require('@geek-fun/jest-search');

startEngine for global setup
stopEngine for global teardown

```jsx
const esSearchConfig = {
  engine: 'elasticsearch', // or 'opensearch' or 'zincsearch'
  version: '8.8.2',
  port: 9600,
  clusterName: 'jest-search-local',
  nodeName: 'jest-search-local',
}
```

**Comment by sibelius** [comment]
```
"@geek-fun/jest-search": "^1.0.2",
```

**Comment by Blankll** [comment]
Hi @sibelius I notice this is due to some network connectivity when downloading the .tar.gz file, pls check:
is there an executable binary under `node_modules/.cache/jest-search/elasticsearch-8.8.2/bin/elasticsearch`?
if no, the most effective solution may be download the related platform's package and decompress it to `node_modules/.cache/jest-search/` for elasticsearch, you can find it in https://www.elastic.co/downloads/elasticsearch

I will try to fix it but it will take some time though

**Comment by sibelius** [comment]
there is not folder here

jest-search downloading binary, url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-darwin-arm64.tar.gz, path: /appi/node_modules/.cache/jest-search/elasticsearch-8.8.2 +0ms
  jest-search Downloaded /app/node_modules/.cache/jest-search/elasticsearch-8.8.2 +362ms
  
  maybe you are missing to create the folders and this is failing

**Comment by sibelius** [comment]
`node_modules/.cache/jest-search` does not exist

**Comment by sibelius** [comment]
- [ ] https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-darwin-arm64.tar.gz is returning 404, not found

**Comment by sibelius** [comment]
- [ ] this is the url of using shelf search package
- [ ] https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-darwin-x86_64.tar.gz

**Comment by Blankll** [comment]
oh, thanks @sibelius , should because I didn't test in the M1 chip yet, I will  try to fix and do some validation in m1

**Comment by Blankll** [comment]
Hi, @sibelius , it should be fixed in the latest version [1.0.5](https://www.npmjs.com/package/@geek-fun/jest-search/v/1.0.5), pls have a try

**Comment by sibelius** [comment]
another error

```
heartbeat error: FetchError: request to http://localhost:9600/ failed, reason: socket hang up +2s
```

**Comment by sibelius** [comment]
more info

```
ConnectionError: other side closed - Local: 127.0.0.1:57883, Remote: 127.0.0.1:9600
```

when doing

```jsx
const esClient = new Client({
      node: config.ELASTICSEARCH,
      maxRetries: 3,
      requestTimeout: 3000,
    });

const result = await esClient.cat.indices({ format: 'json' });
````

**Comment by Blankll** [comment]
Hi @sibelius could you provide more info on how you setup your test is it using the global presets or use startEngine manually? would be great if you provide me a sample test case, it will help me to debug the issue

**Comment by sibelius** [comment]
repro https://github.com/sibelius/jest-search-test

just run `yarn jest`

**Comment by Blankll** [comment]
thanks @sibelius , that's will helpful, I will do some spike and back to you later today

**Comment by Blankll** [comment]
Hi @sibelius the samples you provided working fine with intel chip,, I will try in M1 later, one question: does the failure keep appearing or intermittently?
<img width="833" alt="Screenshot 2023-08-09 at 01 12 33" src="https://github.com/geek-fun/jest-search/assets/28639911/590b9949-afcd-4ae1-a148-cc5ff9fcbe2c">

**Comment by sibelius** [comment]
<img width="1283" alt="image" src="https://github.com/geek-fun/jest-search/assets/2005841/19f7c72e-f0d3-4984-8357-4e1a1113672c">

it always breaks for me

**Comment by Blankll** [comment]
Hi @sibelius, the error in your latest screenshot should be because of the timeout, could you try to increase the timeout config `testTimeout: xx` in jest.config.js?
